### ISSUE TITLE
Important fix display store info and some enhancement

### ISSUE THREAD

**Issue by sagsaw** [covid-maps/covid-maps#102]
We are taking 4 pieces of information from user for one store ... As below 👇🏻

![Screenshot_2020-04-04-20-52-32-838_org mozilla firefox](https://user-images.githubusercontent.com/63158972/78455514-616a2000-768e-11ea-8675-5b25e1b14251.jpg)

But while displaying only one piece of info is identified separately that is the name of store ... Other two info are clubbed together with no visual separation ...

Also most important we are not displaying service type at all ...

![IMG_20200404_213910](https://user-images.githubusercontent.com/63158972/78455567-a8581580-768e-11ea-8719-6c7259ebda28.jpg)

Visually all 4 pieces of information must be separately identified.

**Comment by arjun27** [comment]
will be fixed in #91

**Comment by Siddharth11** [comment]
fixed
