### ISSUE TITLE
Make the geolocation not available message dismissable

### ISSUE THREAD

**Issue by asanjeevrao** [covid-maps/covid-maps#104]
We show this message when the user clicks on locate me without having given location permission - 
![image](https://user-images.githubusercontent.com/39347351/78456560-49c47480-7659-11ea-81b5-05c4377bbeb4.png)

Since there is no CTA on the message it should be dismissable - this is a must have feature

A good to have feature would be to add a CTA to the message and trigger the location permission again

**Comment by sagsaw** [comment]
Upvote ... Must be done. Needed feature.

**Comment by sagsaw** [comment]
PermissionsAPI could be possibly used.

https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API

**Comment by Siddharth11** [comment]
@asanjeevrao I've raised a [PR](https://github.com/covid-maps/covid-maps/pull/141) for this issue
