### ISSUE TITLE
Add a 'Share with friends' option after form submission & update success message copy

### ISSUE THREAD

**Issue by asanjeevrao** [covid-maps/covid-maps#106]
1) Once users successfully submit a form on /update, below the success message we want to add a Share App CTA option that allows users to share the app on their social networks. 

There will be pre-filled copy that needs to be submitted with the share button - 
"Covid Maps - find essentials services around you in the lockdown period - track timings, stock levels and safety precautions at stores. Make an update with info you find in your grocery run and share with neighbours! - https://covidmaps.in/"

Sharing options to include- WhatsApp, Messenger, Instagram, SMS, Copy to ClipBoard, Twitter, GMail

2) Update Success Message copy to - "And now we're up-to-date! Thanks for keeping them coming 🙌"

**Comment by Siddharth11** [comment]
closed by: https://github.com/covid-maps/covid-maps/pull/216
