### ISSUE TITLE
Localization / i18n

### ISSUE THREAD

**Issue by arjun27** [covid-maps/covid-maps#11]
If we're focused on India, the app should show text in Hindi/Kannada, in addition to English

**Comment by phanikishn** [comment]
I would call this i18n  :)

**Comment by sagsaw** [comment]
Why not use Google Translate Service API to translate to the user chosen language as default for the webapp.

This user choice of language can be stored in localstorage.

**Comment by arjun27** [comment]
that's an awesome idea! can you try submitting a PR @sagsaw ?

**Comment by sagsaw** [comment]
Would have loved to but am not REACTive nor NODEal ... Sad  ... Hence testing only ... Suggesting only ...
