### ISSUE TITLE
Add a search feature to allow easy filtering of stores

### ISSUE THREAD

**Issue by asanjeevrao** [covid-maps/covid-maps#115]
With the volume of reviews we're seeing in Bangalore & Vancouver right now, discovering the right locations & updates that have the information you're looking for has become a challenge. To help with this, we need a v1 of search that will allow users to filter results around them based on a search field.

**Comment by asanjeevrao** [comment]
@arjun27 not writing too much detail in the ticket because I'm guessing you're working on this?

**Comment by arjun27** [comment]
closed with latest on master
