### ISSUE TITLE
No data ever loads when using very common and widespread ad-blocker (uBlock Origin)

### ISSUE THREAD

**Issue by gadtfly** [covid-maps/covid-maps#119]
I think one of [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en)'s default blocklists is blocking ipinfo.io, causing:

```
GET https://ipinfo.io/json?token=737774ee26668f net::ERR_BLOCKED_BY_CLIENT

Uncaught (in promise) Error: Network Error
    at createError.js:16
    at XMLHttpRequest.<anonymous> (xhr.js:83)
    at XMLHttpRequest.r (helpers.ts:85)
```

Subsequently, the map and the list below it remains completely unpopulated with stores (though interestly, it does still have the map centered on Vancouver, where I am).

**Comment by arjun27** [comment]
Thanks for reporting and your diagnosis is accurate. It so happens that the fallback in the code (when no location is found) is in Vancouver, so that's purely coincidental.

**Comment by arjun27** [comment]
This is now fixed. Thanks again for reporting.
