### ISSUE TITLE
Bug ... Clicking location nothing happens

### ISSUE THREAD

**Issue by sagsaw** [covid-maps/covid-maps#129]
1. Load covid maps in any browser.
2. If I click location icon first time it take me to my location in maps.
3. Now scroll click load more or click any store.
4. Now again click the location icon as below ...
![IMG_20200407_111853](https://user-images.githubusercontent.com/63158972/78634746-25081100-7894-11ea-9d98-dc0be82ce06f.jpg)

5. Nothing happens. It does not take me to my location.

Both Chrome and Firefox have the same problem.

**Comment by arjun27** [comment]
fixed in #126
