### ISSUE TITLE
Display post submission time with time and day in Store Card

### ISSUE THREAD

**Issue by Sapeksha** [covid-maps/covid-maps#144]
When displaying post submission time on each submission, format the time to show the time at which the submission was created as well as show the day it was posted.

Instead of "2 days ago", display time as "6:45 pm on Sunday". We can follow the below convention for this:
- updates in the last 24 hours: "6:45 pm"
- updates > 24 hours in the last week: "6.45 pm on Sunday"
- updates > 1 week: "6:45 pm 11 days ago"

**Comment by xsihe** [comment]
If no one is working on this right now, I'd like to take a go at it.

**Comment by arjun27** [comment]
Go for it! Feel free to ping/tag me if you need any help :)

**Comment by Siddharth11** [comment]
closed by #254
