### ISSUE TITLE
Create a compressed card view which is shown by default

### ISSUE THREAD

**Issue by asanjeevrao** [covid-maps/covid-maps#150]

**Comment by asanjeevrao** [comment]
Create a compressed card view which is shown by default. The user should have a CTA on the card that allows them to expand it. 

Details in compressed view - 


Details in expanded view -

**Comment by Sapeksha** [comment]
![image](https://user-images.githubusercontent.com/3829883/78970500-4e0bea00-7abe-11ea-922c-7fd0a8f1ab3f.jpeg)

**Comment by Siddharth11** [comment]
closed by: https://github.com/covid-maps/covid-maps/pull/247
