### ISSUE TITLE
Store selection bug - multiple stores with same lat long 

### ISSUE THREAD

**Issue by asanjeevrao** [covid-maps/covid-maps#159]
to repro - search for Bangalore, find Hareesh Store click directions it opens in new tab, come back to the page and you don't see the listing

Happening because in Bangalore there are multiple stores with no place iD and the same lat-long (likely Blr IP)

Two fixes - 
1) Clicks on directions should not be treated as a click on the card, i.e. card remains at same position 
2) When defining the selected card, use both lat-long and name to define the selection

**Comment by arjun27** [comment]
Solution: update `state.selectedLocation` in Homepage component to use both location and name

**Comment by arjun27** [comment]
or `storeId` now, since we have it after #186
