### ISSUE TITLE
Add fields for Flag and Deleted in Store Info table in DB

### ISSUE THREAD

**Issue by sampoorna** [covid-maps/covid-maps#165]
This is necessary to be able to filter out which reviews we're showing on the front-end, as we don't want to permanently delete reviews.

Flag - Should be a small int. Will use a mapping to determine which number corresponds to which reason. It will be publicly viewable, perhaps added to Notion.
Deleted - Should be boolean.

**Comment by arjun27** [comment]
> Flag - Should be a small int. Will use a mapping to determine which number corresponds to which reason. It will be publicly viewable, perhaps added to Notion.

Why not enum strings? Having a mapping will obscure it out for newcomers.

I'm not entirely sure why we need deleted? I was thinking of deleted as a derivative of the flag. Eg, flagged as `duplicate` would mean it is not shown anywhere, and therefore "deleted". Is there a scenario I'm missing?

Reason is that I want to minimize the fields, since they will also need to be indexed in the database. Every new index slows down inserts.

**Comment by sampoorna** [comment]
Enum can also work. Mapping can be hosted in a place that is easily accessible for newcomers, but enum works too.

And the reason for flagged and deleted is to differentiate between what needs to be reviewed vs what has been reviewed. It's possible to combine the two, but we would lose information in some cases. For eg., what if we find some instances that are obv spam but aren't covered by the automatic flagging logic yet? We can mark them as deleted without touching the flag field.

Conceptually, the two fields are approximations for the two systems at work: automatic and manual. It will be useful to keep them separate so we can track how each is functioning. If you're concerned about indexing, we don't need to index the flag column. At least for web queries, we can only focus on what's deleted vs what's not.

**Comment by arjun27** [comment]
> For eg., what if we find some instances that are obv spam but aren't covered by the automatic flagging logic yet? We can mark them as deleted without touching the flag field. 

This seems to miss the point of the flagged field imo. In this scenario, I would prefer flagging it with the enum reason of spam. I would like to minimize rows marked as deleted without a flagging reason

**Comment by arjun27** [comment]
The need to differentiate between manual and automated. In that case, should `deleted` be called `manually_deleted`?

**Comment by arjun27** [comment]
Just for my clarity, can you share the possible values of the flagged reason field?

**Comment by sampoorna** [comment]
For now, the possible values are:
- Empty lat/long
- Invalid store name
- Very short reviews
- Short reviews
- Spammy words
- Duplicate

The ideal workflow is supposed to have automated delete and manual delete, in which case `manually_deleted` doesn't work, so maybe we can stick to `deleted`. Essentially `flag` models the prediction, and `deleted` models the ground truth. Over time we would expect them to come very close, in which case we don't need to have separate fields, but right now, our spam model would need to know what it predicted vs what the ground truth was.

**Comment by sampoorna** [comment]
> I would like to minimize rows marked as deleted without a flagging reason

We can come up with another enum for human validation that covers the reasons. But would like to keep human validation separate from model predictions for now. That's the intent.

**Comment by arjun27** [comment]
I think I understand the enum reasons you have shared but I’m still not entirely sure of:

1. Is there a case where a particular flagging reason will have different values for deleted? Eg, if a row is marked to have empty lat-lng, will it always be deleted? 

2. Is there a case where deleted will be true but flagged reason will be empty? 

3. What will the query API endpoint use to filter the rows - flagged or deleted?

**Comment by sampoorna** [comment]
1. No, empty lat/long should always be deleted, and there's no ambiguity there. But short reviews for eg., can still be useful.
2. It can be, if a human mod finds something delete-worthy that's not covered by existing flag enums
3. Should be deleted, that way, people can still see the submission they made (otherwise they might get frustrated and submit again and again). But we could move to a hide-by-default model later on. Something to consider once our model of spam becomes better AND when the volume of submissions is so high, that it doesn't hurt to delay posting AND our human mods can validate more quickly. For now, we can continue to show-by-default as we've been doing.

**Comment by sampoorna** [comment]
> Is there a case where a particular flagging reason will have different values for deleted?

Just to clarify, deleted is a bool field. So it's not a multi-class categorisation problem, we don't care whether the exact classes are perfect as long as we're detecting spam under SOME class.
