### ISSUE TITLE
When at a higher zoom level, show marker clusters

### ISSUE THREAD

**Issue by Sapeksha** [covid-maps/covid-maps#172]
In Bangalore, there are way too many pins on the Map. This is a good thing in terms of showing customers we have a lot of data - but it is overwhelming for customers to process.

Show one pin as a representation of all pins in a certain location radius.

**Comment by preetjdp** [comment]
This can be used.
https://tomchentw.github.io/react-google-maps/#!/MarkerClusterer/1

Would have to figure out how to change from cluster to markers on zoom
