### ISSUE TITLE
Make Search bar sticky along with the Page header

### ISSUE THREAD

**Issue by Sapeksha** [covid-maps/covid-maps#173]
When scrolling, the search bar hides as it goes out of view. Making it stick along with the header will help users have quick access to it no matter how much they've scrolled.

**Comment by asanjeevrao** [comment]
Makes sense - I don't see the value in the header being sticky though, unless we add some useful navigation elements there. With this change, we could make the header not sticky, but just the search bar sticky

**Comment by Sapeksha** [comment]
Makes sense. I just feel like it’s easy for people to forget that there is a search bar. Most UIs today tend to keep reminding people that searching is possible. Maybe we hold off until a few filter experiences are possible then?
