### ISSUE TITLE
Capitalize first letters of each word in Store Name

### ISSUE THREAD

**Issue by asanjeevrao** [covid-maps/covid-maps#248]
While displaying store name on the website, capitalize the first letters of each word. For the most part these are mistakes made by users while entering store names - makes 
![WhatsApp Image 2020-04-15 at 15 32 36](https://user-images.githubusercontent.com/39347351/79395398-65b7f800-7f2e-11ea-97f9-8785dfc12b21.jpeg)

This should be shown as The Aquarium Store. To keep things consistent on the /Update page too, we could make this change before we store the store name in the DB

**Comment by piyush85** [comment]
Plz assign this issue to me

**Comment by Siddharth11** [comment]
@piyush85 you can pick this up now

**Comment by Siddharth11** [comment]
@asanjeevrao do we really need to format users' input before sending it to DB? Isn't it better to just capitalize the store name on the card itself?

**Comment by asanjeevrao** [comment]
@Siddharth11 yes that works too! I thought fixing before storing in the DB will make sure that even on Location & Update pages the store names will be formatted correctly - but you're right it can be handled on the front end as well
