### ISSUE TITLE
Add text next to CTA icons on store cards 

### ISSUE THREAD

**Issue by asanjeevrao** [covid-maps/covid-maps#250]
CTA for share to to include text 'Share' with the share icon
CTA for directions to include text 'Open in Maps' with the directions icon

**Comment by asanjeevrao** [comment]
Also, change 'Update' on Store Cards to 'Add Update'

**Comment by Siddharth11** [comment]
@asanjeevrao where will be position these CTA's ? At the bottom of the card ?

**Comment by asanjeevrao** [comment]
Indicative design here - https://projects.invisionapp.com/share/J2WUJTOZ7QM#/screens/413822264

We are not doing exactly what's on the design though - 
1) Update CTA (now called 'Add Update') will continue to be at the current position 
2) Directions & Share CTA will move to the bottom of the store card as per the design. Copy next to share icon - 'Share'; copy next to Maps icon - 'Open in Maps'
