### ISSUE TITLE
Show distance value in the store cards

### ISSUE THREAD

**Issue by arjun27** [covid-maps/covid-maps#282]
Feature request from @spdongre: "Stores nearby should have facility to mention the radius 1 Km, 3 Km, 5 Km, 8 km, 10 km etc."

**Comment by arjun27** [comment]
Yes! We have sorting by distance, and extracting the value should be possible. Let me know if you need any help :)

**Comment by xsihe** [comment]
I would like to ask if the metric system is enough, or if imperial units (miles) are also needed. Also, is the positioning ok or should it be moved to somewhere else? 
![image](https://user-images.githubusercontent.com/22055750/80168729-9b558480-85b1-11ea-9936-3e5aeb68ea75.png)

**Comment by arjun27** [comment]
I think this is a great start!
