### ISSUE TITLE
New location card showing up again after dismissing

### ISSUE THREAD

**Issue by asanjeevrao** [covid-maps/covid-maps#289]
To reproduce search for a store that doesn't have a listing. Dismiss the new store card. Go to a different page and come back to home page, the blue card appears again. 

https://www.loom.com/share/e65c206b33e4455dbeb8f456c8acb470

**Comment by Siddharth11** [comment]
@xsihe would you like to pick this up?

**Comment by xsihe** [comment]
> @xsihe would you like to pick this up?

I take it that after dismissing the card, you would want it to pop up again only if the user clicks 'search' with the same location (or a different unregistered address) afterwards? Meaning, no pop up when we go back and forth between pages or reloading the page?

**Comment by Siddharth11** [comment]
Yes

**Comment by xsihe** [comment]
Okay, I'll try fixing it.

**Comment by Siddharth11** [comment]
Let me know if you need any help.
