### ISSUE TITLE
Distance calculation bug 

### ISSUE THREAD

**Issue by asanjeevrao** [covid-maps/covid-maps#298]
when users search for a location using the search bar, the distances of stores are being calculated from the searched pin's location. Distances from stores should always be shown from current location.
Eg: when I search for 'Bangalore' but my current location is Vancouver
https://user-images.githubusercontent.com/39347351/80301714-9253e700-875a-11ea-9d39-daf7d8b69b17.png

Relates to https://github.com/covid-maps/covid-maps/pull/287

**Comment by xsihe** [comment]
I'll work on it.
