### ISSUE TITLE
Indicate Store or Service type for each Store Card View on Home page

### ISSUE THREAD

**Issue by sampoorna** [covid-maps/covid-maps#69]
Convey type of store to user easily by displaying this information in each Store Card view.
This can be done in either of the following ways:

1. As subtext below Store Name (similar to Address)
2. Showing separate icons for different kinds of stores
3. Simple card color for different kinds of stores

1 & 2 might work for cases where a single place falls under 2 or more categories.

**Comment by xsihe** [comment]
Would something like this be okay?
![image](https://user-images.githubusercontent.com/22055750/79938056-8352f900-8429-11ea-8a6a-bbea5834abe0.png)

**Comment by sampoorna** [comment]
@xsihe We're replacing this with [availability tags](https://github.com/covid-maps/covid-maps/pull/262). We can probably close this one out now.
