### ISSUE TITLE
Add a clear button to the store card callout on home page when user searches for a new store

### ISSUE THREAD

**Issue by asanjeevrao** [covid-maps/covid-maps#73]

**Comment by xsihe** [comment]
Do you mean adding a clear/delete button to the teal card below?
![image](https://user-images.githubusercontent.com/22055750/79659724-cf7c1000-8181-11ea-8986-61e0bc66bcec.png)

**Comment by asanjeevrao** [comment]
Yes! I was imagining a simple 'x' style action at the top right corner of this card that helps you dismiss this card

**Comment by xsihe** [comment]
Okay, I'll work on it.
