### ISSUE TITLE
Bug when submitting information about multiple locations in succession

### ISSUE THREAD

**Issue by sampoorna** [covid-maps/covid-maps#93]
1. Search for location on homepage
2. Click on add. Change type to "Other", add and submit info.
3. On the same page (submit) search for new location
4. When you select location, the store name is updated, the dropdown type continues to show "Other".
5. Fill out other info and hit submit.
6. On the spreadsheet, second location is stored as "Grocery" even though on the form it was showing up as "Other"

**Comment by arjun27** [comment]
searching on submit page is now disabled
