### ISSUE TITLE
uBlock/Ghostery - Could not submit update

### ISSUE THREAD

**Issue by sachdevaprash** [covid-maps/covid-maps#94]
When using privacy add-ons on Firefox, submission of the update failed and it was stuck on "Submitting" with no errors.

I understand that this may not be an urgent issue, but an advisory to switch off those add-ons for the site may help.

**Comment by arjun27** [comment]
related to #67 and #47

**Comment by sachdevaprash** [comment]
Map does not work with uBlock anymore. Can't even see pins. It works after switching off uBlock.
