### ISSUE TITLE
Home Page Feed Issues

### ISSUE THREAD

**Issue by Sapeksha** [covid-maps/covid-maps#95]
#89 - Include a 'Add to Home Screen' CTA on home page
#84 - Display static information as part of each Store Card View
#82 - Display relevant UGC as part of each Store Card View
#73 - Add a clear button to the Store Card View on home page when user searches for a new store
#74 - Add Messaging about number of users on the app
#69 - Indicate Store or Service type for each Store Card View on Home page
#65 - Expose Locality/Address in the Store Card View
#55 - Homepage filters for type of service
#4   - Add information from G Maps to location card

**Comment by sampoorna** [comment]
#43 and #89 seem to be duplicates. Also #84 and #4 and #65

**Comment by Sapeksha** [comment]
Yes will clean this up now. I justttt created this.

**Comment by sampoorna** [comment]
Just wanted to highlight it so it's easier to do 😀 We should probably close out the duplicates.

**Comment by Sapeksha** [comment]
Collating everything in single prioritized list.
